### PR TITLE
Add ForceTempUrl

### PR DESCRIPTION
**Pull request by lcarstensen**
Also if you're still working this branch, I also added a small patch to allow one to force use of tempurl for HP Public Cloud's Swift implementation, which doesn't provide a proper /info autodiscovery endpoint.

### CODE REVIEW

**Comment by lebauce** [comment]
Thanks for your PR. I didn't know that `/info` was not accessible on HP Cloud.

I made the following modifications to handle servers that disabled the `/info` feature:
2 new parameters can be specified in the configuration file:
- `TempURLContainerKey` is a boolean that, when set to True, tells the registry to use container secret key instead of account secret key
- `TempURLMethods` is an array of string of the supported HTTP methods.

IIRC, for HP Public Cloud should have in its configuration file:

```
- tempurlcontainerkey: true
- tempurlmethods:
  - GET
  - PUT
  - HEAD
  - POST
  - DELETE
```

I updated my `swift-temp-url` branch. Could you please give it a try and tell me if it works on HP Cloud ?

Thanks !

**Comment by lcarstensen** [comment]
Thanks for doing that work!  And sorry it took a little bit to catch back up.

Unfortunately there are some more HP-isms.  HP Public Cloud's tempurl format is actually slightly different from Swift upstream in that it includes the tenantid and a secret key id into the temp_url_sig= component of the URL, separated by colons.

I've updated my branch, and it "works for me".  I'm not sure if we'll get to the point where it ever makes sense to carry my extras for HP Public Cloud, but otherwise this is working.

I am noticing some instability on "docker pull" itself when the docker daemon gets passed a URL to download that it then gets a 401 unauthorized when it requests it.  I'm tracking that down elsewhere, but I'm seeing that pulling layers from a buggy registry can cause the docker daemon to crash.  I've also seen some similar crashes where there is high network loading, so I don't think this is exclusive to the 307 redirect work.

**Comment by lebauce** [comment]
@lcarstensen I created an account on HP Cloud for testing.

I updated my branch with your change. I renamed `SecretID` by `AccessKey`.
Regarding the 401 error, it may be related to the fact that, on HP Cloud, a "HEAD" on a temporary URL is allowed only if the signature was generated with "GET" or "POST" (https://github.com/lebauce/distribution/blob/swift-temp-url/registry/storage/driver/swift/swift.go#L671-L673).

Could you give it a try ? Thanks !

**Comment by lcarstensen** [comment]
Your branch works for me now, thanks for all your efforts!  I'll close this PR out.

**Pull request closed without merging**
